version: '3.5'

networks:
  dmrunner:
    driver: bridge

services:
  elasticsearch:
    networks:
      - dmrunner
  postgres:
    networks:
      - dmrunner

  nginx:
    image: "nginx:1.14-alpine"
    ports:
      - "80:80"
    volumes:
      - "./dmrunner-nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - dmrunner
  s3:
    networks:
      - dmrunner
  redis:
    networks:
      - dmrunner
